PREPROCESS:
  stack_name : 'E145_005' # name you want the output stack to have
  img_source : 'img/backup/ACHIMG/E165_005'
  img_destination : 'img/train/ACH/img/E145_005'
  mask_source : ''
  mask_destination : 'img/train/ACH/mask/E145_000'

TRAIN:
  imgdir : 'img/train/ACH/E165'
  modeldir : 'models'
  pretrained_model : 'models/E165_M02042022/10000.ckpt'
  logdir : 'logs'
  batch_size : 8
  iter_num : 10000

TEST:
  imgdir : 'img/test/ACH'
  logdir : 'logs'
  resultdir : 'results'
  result_temp_dir : 'intermediate'
  test_stack : 'E165_012'
  trained_model :  'models/E145_M02272022/20000.ckpt' #'models/E145_M01072022/20000.ckpt' 
  iter_num : 20000
  batch_size : 8
  threshold : 100